name: preview_server
description: The Monarch Preview Server
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  monarch_utils: ^1.0.0
  monarch_definitions:
    path: ../packages/monarch_definitions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
