name: monarch_annotations
description: Annotations for Monarch. Monarch is a tool for building Flutter widgets in isolation. It makes it easy to build, test and debug complex UIs.
version: 1.1.0
homepage: https://monarchapp.io
repository: https://github.com/Dropsource/monarch
issue_tracker: https://github.com/Dropsource/monarch/issues
documentation: https://monarchapp.io/docs/introduction
topics:
  - tool
  - ui
  - monarch
  - stories

environment:
  sdk: ^3.2.0
