name: dropsource_storybook_utils
description: A starting point for Dart libraries or applications.
version: 0.0.2
# homepage: https://www.example.com
# author: Fernando Trigoso <fertrig@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
