name: monarch_io_utils
description: Monarch utilities for dart io and other dart sdk packages.
version: 1.3.0
homepage: https://monarchapp.io
repository: https://github.com/Dropsource/monarch
issue_tracker: https://github.com/Dropsource/monarch/issues
documentation: https://monarchapp.io/docs/introduction

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
