name: monarch_io_utils
description: Utilities for dart io and other dart sdk packages.
version: 1.1.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
