name: preview_api
description: The Monarch Preview API
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  monarch_utils: ^1.0.0
  monarch_definitions:
    path: ../packages/monarch_definitions
  monarch_grpc:
    path: ../packages/monarch_grpc
  grpc: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
