name: preview_api
description: The Monarch Preview API
publish_to: 'none'
version: 2.5.1

environment:
  sdk: ^3.2.0
  flutter: '>=3.22.0-0.1.pre'

dependencies:
  flutter:
    sdk: flutter
  monarch_utils: ^1.2.0
  monarch_io_utils: ^1.4.0
  monarch_definitions: ^1.7.0
  monarch_grpc: ^2.4.0
  grpc: ^4.0.1
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
