name: preview_api
description: The Monarch Preview API
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  monarch_utils: ^1.0.0
  monarch_io_utils: ^1.2.0
  monarch_definitions: ^1.2.0
  monarch_grpc: ^2.0.0
  grpc: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  monarch_io_utils:
    path: ../packages/monarch_io_utils
  monarch_grpc:
    path: ../packages/monarch_grpc

flutter:
