name: monarch_cli
description: Command-line interface for Monarch binaries.
version: 2.1.5
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  pubspec_parse: ^1.0.0
  checked_yaml: ^2.0.1
  uuid: ^3.0.4
  pub_semver: ^2.0.0
  args: ^2.1.0
  yaml_edit: ^2.0.0
  package_config: ^2.0.2
  path: ^1.8.2
  meta: ^1.8.0
  io: ^1.0.3
  yaml: ^3.1.1
  grpc: ^3.1.0
  http: ^0.13.5
  monarch_utils: ^1.0.4
  monarch_http: ^1.2.0
  monarch_io_utils: ^1.2.0
  monarch_grpc: ^1.0.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.17.2
  mockito: ^5.0.7
  build_runner:

dependency_overrides:
  monarch_io_utils:
    path: ../packages/monarch_io_utils