name: monarch_annotations
description: Contains annotations for monarch. Monarch lets you generate stories for your widgets.
version: 0.1.0
homepage: https://github.com/Dropsource/monarch

environment:
  sdk: '>=2.12.0 <3.0.0'
