name: monarch_annotations
description: Contains annotations for monarch. Monarch lets you generate stories for your widgets.
version: 0.1.1
homepage: https://monarchapp.io
repository: https://github.com/Dropsource/monarch
issue_tracker: https://github.com/Dropsource/monarch/issues
documentation: https://monarchapp.io/docs/introduction

environment:
  sdk: '>=2.12.0 <3.0.0'
