name: monarch_utils
description: Utilities for the monarch package. Mostly utilities for logging.
version: 0.0.16
homepage: https://github.com/Dropsource/monarch

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
