name: monarch_utils
description: Utilities for the monarch package. Mostly utilities for logging.
version: 0.1.2
homepage: https://monarchapp.io
repository: https://github.com/Dropsource/monarch
issue_tracker: https://github.com/Dropsource/monarch/issues
documentation: https://monarchapp.io/docs/introduction

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
