name: monarch_utils
description: Utilities for the monarch package. Monarch is a tool for building Flutter widgets in isolation. It makes building beautiful apps a simpler and faster experience.
version: 1.0.3
homepage: https://monarchapp.io
repository: https://github.com/Dropsource/monarch
issue_tracker: https://github.com/Dropsource/monarch/issues
documentation: https://monarchapp.io/docs/introduction

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
