name: monarch_utils
description: Utils for monarch.
version: 0.0.8
homepage: https://github.com/Dropsource/monarch

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
