builders:

  meta_localizations_builder:
    import: 'package:monarch/stories_builder_factories.dart'
    builder_factories: ['metaLocalizationsBuilder']
    build_extensions: {
      '.dart': ['.meta_localizations.g.dart']
    }
    build_to: cache
    auto_apply: root_package
    runs_before: ['monarch|meta_themes_builder']

  meta_themes_builder:
    import: 'package:monarch/stories_builder_factories.dart'
    builder_factories: ['metaThemesBuilder']
    build_extensions: {
      '.dart': ['.meta_themes.g.dart']
    }
    build_to: cache
    auto_apply: root_package
    runs_before: ['monarch|meta_stories_builder']
    defaults:
      generate_for:
        exclude: ['**.meta_localizations.g.dart']

  meta_stories_builder:
    import: 'package:monarch/stories_builder_factories.dart'
    builder_factories: ['metaStoriesBuilder']
    build_extensions: {
      '.dart': ['.meta_stories.g.dart'],
    }
    build_to: cache
    auto_apply: root_package
    runs_before: ['monarch|main_builder']
    defaults:
      generate_for:
        include: ['**_stories.dart']

  main_builder:
    import: 'package:monarch/stories_builder_factories.dart'
    builder_factories: ['mainBuilder']
    build_extensions: { '$lib$' : ['main_monarch.g.dart']}
    build_to: cache
    auto_apply: root_package
