name: monarch
description: Code generator for Monarch.
version: 0.0.21
homepage: https://github.com/Dropsource/monarch

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^1.2.2
  source_gen: ^0.9.5
  dart_style: ^1.3.3
  monarch_annotations: 0.0.7
  monarch_utils: 0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:

