name: monarch
description: Code generator for Monarch. Monarch lets you generate stories for your widgets.
version: 0.2.0
homepage: https://github.com/Dropsource/monarch

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build: ^2.0.0
  source_gen: ^1.0.0
  dart_style: ^2.0.0
  monarch_annotations: ^0.1.0
  monarch_utils: ^0.1.0
  pedantic: ^1.11.0
  glob: ^2.0.1
  analyzer: ^1.3.0
  path: ^1.8.0
  vm_service: ^6.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

