name: monarch
description: Code generator for Monarch. Monarch is a tool for Flutter developers. It makes building beautiful apps a simpler and faster experience.
version: 1.0.0
homepage: https://monarchapp.io
repository: https://github.com/Dropsource/monarch
issue_tracker: https://github.com/Dropsource/monarch/issues
documentation: https://monarchapp.io/docs/introduction


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build: ^2.0.0
  source_gen: ^1.0.0
  dart_style: ^2.0.0
  monarch_annotations: ^0.1.0
  monarch_utils: ^0.1.1
  pedantic: ^1.11.0
  glob: ^2.0.1
  analyzer: ^1.3.0
  path: ^1.8.0
  vm_service: ^6.2.0
  meta: ^1.3.0
  flutter_test:
    sdk: flutter

dev_dependencies:

flutter:

