name: monarch
description: Code generator for Monarch. Monarch is a tool for building Flutter widgets in isolation. It makes it easy to build, test and debug complex UIs.
version: 2.1.2
homepage: https://monarchapp.io
repository: https://github.com/Dropsource/monarch
issue_tracker: https://github.com/Dropsource/monarch/issues
documentation: https://monarchapp.io/docs/introduction


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build: ^2.0.0
  source_gen: ^1.0.0
  dart_style: ^2.0.0
  monarch_annotations: ^1.0.0
  monarch_utils: ^1.0.0
  glob: ^2.0.1
  analyzer: ^2.3.0
  path: ^1.8.0
  vm_service: ^7.3.0
  meta: ^1.3.0
  stack_trace: ^1.10.0
  flutter_test:
    sdk: flutter

dev_dependencies: 
  lints: ^1.0.1

flutter:

