name: monarch
description: Code generator for Monarch. Monarch lets you generate stories for your widgets.
version: 0.0.25
homepage: https://github.com/Dropsource/monarch

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build: ^1.2.2
  source_gen: ^0.9.5
  dart_style: ^1.3.3
  monarch_annotations: ^0.0.10
  monarch_utils: ^0.0.13
  pedantic: ^1.8.0
  glob: ^1.2.0
  analyzer: ^0.39.8
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

