# Build settings for Monarch Windows app

# Version of the Monarch Windows app. Avoid pre-releases until
# we have tested that the Windows build works with pre-releases.
version: 2.3.1

# Relative path from gen\runner directory. Use double back-slashes.
app_icon_path: ..\\..\\src\\resources\\monarch_app_icon.ico
