name: monarch_http
description: Http utilities for Monarch. Monarch is a tool for building Flutter widgets in isolation. It makes it easy to build, test and debug complex UIs.
version: 1.3.1
homepage: https://monarchapp.io
repository: https://github.com/Dropsource/monarch
issue_tracker: https://github.com/Dropsource/monarch/issues
documentation: https://monarchapp.io/docs/introduction

environment:
  sdk: ^3.2.0

dependencies:
  http: ^1.3.0
  monarch_utils: ^1.2.0

dev_dependencies:
  lints: ^5.1.1
