name: monarch_tools
description: 
version: 

environment:
  sdk: ^3.2.0

dev_dependencies:
  path:
  yaml:
  pub_semver:
  args:
  monarch_utils:
    path: ../packages/monarch_utils/
  monarch_io_utils:
    path: ../packages/monarch_io_utils/
