platform :osx, '10.14'
use_frameworks!

target 'monarch_macos' do
  pod 'FlutterMacOS'
  # Add plugins as needed
end

# The post_install block is optional but recommended if users encounter 
# version mismatches between their SDK and the Pods-embedded framework.
# post_install do |installer|
#   ...
# end
