# Flutter actions:
# https://github.com/marketplace/actions/flutter-action

# Dart actions:
# https://github.com/dart-lang/setup-dart

# Other workflow yaml samples:
# - https://github.com/dart-lang/build/blob/master/.github/workflows/dart.yml
# - https://github.com/dart-lang/setup-dart
# - https://github.com/dart-lang/markdown/blob/master/.github/workflows/test-package.yml

name: Monarch Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_monarch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta' # or: 'stable', 'beta', 'dev' or 'master'
          
      - name: Install dependencies
        working-directory: packages/monarch
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        working-directory: packages/monarch
        run: flutter analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        working-directory: packages/monarch
        run: flutter test
        
  test_monarch_utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        working-directory: packages/monarch_utils
        run: dart pub get
      - name: Analyze project source
        working-directory: packages/monarch_utils
        run: dart analyze
      - name: Run tests
        working-directory: packages/monarch_utils
        run: dart test

  test_monarch_io_utils:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        working-directory: packages/monarch_io_utils
        run: dart pub get
      - name: Analyze project source
        working-directory: packages/monarch_io_utils
        run: dart analyze
      - name: Run tests
        working-directory: packages/monarch_io_utils
        run: dart test
